version: '3.3'

services:
  mongo_dev_smarthotel:
    image: mongo:7.0        
    container_name: mongo_dev_smarthotel
    ports:      
       - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - mongodb_data_dev_smarthotel:/data/db      
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "${MONGODB_PORT:-27017}"]  
    healthcheck:
      test: |
        mongosh --port ${MONGODB_PORT:-27017} --eval "
          if (!rs.isMaster().ismaster) {
            rs.initiate({
              _id: 'rs0',
              members: [{ _id: 0, host: '${MONGODB_RS_HOST:-localhost}:${MONGODB_PORT:-27017}' }]
            });
          }
        "
      interval: 10s
      timeout: 5s    
      retries: 3  

  redis_dev_smarthotel:
    image: redis:alpine
    container_name: redis_dev_smarthotel
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data_dev_smarthotel:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3    

volumes:  
  mongodb_data_dev_smarthotel: ~
  redis_data_dev_smarthotel: ~